services:
  banking-api:
    build: 
      context: ../banking-api/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ../banking-api/api:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - banking-network

  banking-web:
    build:
      context: ../banking-web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      # Use proxy endpoint for local development (mimics production ingress)
      - VITE_API_URL=/api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      banking-api:
        condition: service_healthy
    networks:
      - banking-network

  data-seeder:
    build:
      context: .
      dockerfile: Dockerfile.seed
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      banking-api:
        condition: service_healthy
    networks:
      - banking-network
    restart: "no"  # Run once and exit

networks:
  banking-network:
    driver: bridge
